// Om du kör andra portar på annat än standard (3000)
// ändra 3000 i länkarna till porten du kör servern på

###
// Rest client gör exakt samma sak som en fetch fast http anrop och får svar tillbaka

//Hämta alla skor
GET http://localhost:3000/shoes

###

//Hämta en sko
GET http://localhost:3000/shoes/1

###

//Lägg till en sko
POST http://localhost:3000/shoes
Content-Type: application/json

{
    "id": 5,
    "brand": "NewBrand",
    "size": "38",
    "price": 1900
}

###

DELETE http://localhost:3000/shoes/2


###


// Byt ut till annan sko
PUT http://localhost:3000/update/3
Content-Type: application/json

{
    "id": 3,
    "brand": "putBrand",
    "size": "37",
    "price": 1800
}